- name: Create ec2 and r53 records
  hosts:  all
  connection: local   
  vars:
    sg_id: sg-0cfcd5040a31b76f2
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
    - mongdb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type:  "t3.micro"
      security_group: "{{ sg_id }}"  
      image_id: "{{ ami_id }}"        
      name: "{{ item }}-{{ environment }}"
      tags:
        Project:  roboshop
        Component:  "{{ item }}"
        Environment:  "{{ env }}"
        Name: "{{ item }}-{{ environment }}" 
    loop: "{{ instances }}"
    register: ec2_output

  - name:  print output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

