- name: Configure shipping service
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql  

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete shipping zip code
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent    

  - name: download shipping
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unarchive shipping
    ansible.builtin.unarchive:
      src:  /tmp/shipping.zip
      dest: /app
      remote_src: yes           #yes - source code already present on the remote server.  no - copies it to remote and then extract
  
  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app
  
  - name: install dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy systemctl service
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: import shipping data
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: Roboshop@1
      target: "{{ item }}"
    loop: 
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes  
    





      


